name: fanoseq
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow
  - scipy
  - scikit-learn
  - statsmodels
  - biopython
  - scikit-bio
  - numba
  - duckdb
  - polars
  - zarr
  - h5py
  - networkx
  - matplotlib
  - seaborn
  - umap-learn
  - pyyaml
  - tqdm
  - jupyterlab
  - ipykernel
  - typer
  - rich
  - pytest
  - ruff
  - mypy
  - pip
  - pip:
      - pyfastx
      - build
      - twine
